// NeuronClient/FontData.h
//
// GENERATED by Tools/BakeFont.py -- do not edit by hand; edit the tool or its inputs and run it again.
//
// The metrics of the desk's text faces (ADR-016): the cell row every face is baked to, each face's advance and
// baseline, and the size of its coverage. Cheap to include anywhere; the bytes themselves are in FontCoverage.h.
//
// Baked 2026-09-16 by Tools/BakeFont.py with Pillow 12.3.0 on FreeType 2.14.3, Python 3.14.2.
//
// Sources (https://github.com/google/fonts/tree/main/ofl/ibmplexmono):
//   IBMPlexMono-Regular.ttf: Version 2.3; SHA-256 6a3412f058c7d8dfd9170c41e85ade48e5156ecb89356110ca57a0a27734af46
//   IBMPlexMono-SemiBold.ttf: Version 2.3; SHA-256 d3c38e55c78f5b0f28009fddba4834ec503278936a5986032424c9bd2d23aa46
//   OFL.txt: SHA-256 7e6b2818edbd8f6a01ae80641cc8f16a51080d08fb4e532be3a0b6f74adb07da
//
// Faces (Font.h): BODY = Regular 20 px, 12 px advance; SMALL = Regular 16.67 px, 10 px advance; TITLE = SemiBold 20 px, 12 px advance
// Every face is 24 px tall, which is the cell row (UI section 1).
#pragma once

#include <cstddef>
#include <cstdint>

namespace Neuron
{

inline constexpr std::uint32_t FONT_FIRST_CODEPOINT = 0x20;
inline constexpr std::uint32_t FONT_GLYPH_COUNT = 96;
inline constexpr std::uint32_t FONT_LINE_HEIGHT_PIXELS = 24;

inline constexpr std::uint32_t FONT_BODY_ADVANCE_PIXELS = 12;
inline constexpr std::uint32_t FONT_BODY_BASELINE_PIXELS = 19;
inline constexpr std::size_t FONT_BODY_BYTES =
  static_cast<std::size_t>(FONT_GLYPH_COUNT) * FONT_BODY_ADVANCE_PIXELS * FONT_LINE_HEIGHT_PIXELS;

inline constexpr std::uint32_t FONT_SMALL_ADVANCE_PIXELS = 10;
inline constexpr std::uint32_t FONT_SMALL_BASELINE_PIXELS = 18;
inline constexpr std::size_t FONT_SMALL_BYTES =
  static_cast<std::size_t>(FONT_GLYPH_COUNT) * FONT_SMALL_ADVANCE_PIXELS * FONT_LINE_HEIGHT_PIXELS;

inline constexpr std::uint32_t FONT_TITLE_ADVANCE_PIXELS = 12;
inline constexpr std::uint32_t FONT_TITLE_BASELINE_PIXELS = 19;
inline constexpr std::size_t FONT_TITLE_BYTES =
  static_cast<std::size_t>(FONT_GLYPH_COUNT) * FONT_TITLE_ADVANCE_PIXELS * FONT_LINE_HEIGHT_PIXELS;

} // namespace Neuron
